### ISSUE TITLE
Warnings with webapp-generator out of the box

### ISSUE THREAD

**Issue by lizzzzard** [yeoman/generator-webapp_DEPRECATED#210]
with a fresh install of the webapp via `yo webapp`, i get the following warning when doing `grunt server` or `grunt`:

```
Running "jshint:all" (jshint) task

Gruntfile.js
  line 304  col 7  Expected 'grunt' to have an indentation at 9 instead at 7.
  line 305  col 7  Expected 'grunt' to have an indentation at 9 instead at 7.

2 problems

Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.
```

Also, compass throws a warning:

```
Running "htmlmin:dist" (htmlmin) task
File dist/404.html created.
File dist/index.html created.

Done, without errors.
    Warning:
    D:\testyo\node_modules\grunt-contrib-compass\node_modules\tmp\lib\tmp.js:261
      throw err;
            ^
    TypeError: Cannot read property 'stdout' of undefined
        at compile (D:\testyo\node_modules\grunt-contrib-compass\tasks\compass.js:39:10)
        at D:\testyo\node_modules\grunt-contrib-compass\tasks\compass.js:70:7
        at D:\testyo\node_modules\grunt-contrib-compass\tasks\lib\compass.js:121:11
        at _fileCreated (D:\testyo\node_modules\grunt-contrib-compass\node_modules\tmp\lib\tmp.js:172:7)
        at OpenReq.Req.done (D:\testyo\node_modules\grunt-contrib-imagemin\node_modules\gifsicle\node_modules\bin-wrapper\node_modules\download\node_modules\decompress\node_modules\tar\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:142:5)
        at OpenReq.done (D:\testyo\node_modules\grunt-contrib-imagemin\node_modules\gifsicle\node_modules\bin-wrapper\node_modules\download\node_modules\decompress\node_modules\tar\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:64:22)
        at OpenReq.Req.done (D:\testyo\node_modules\grunt-contrib-imagemin\node_modules\gifsicle\node_modules\bin-wrapper\node_modules\download\node_modules\decompress\node_modules\rimraf\node_modules\graceful-fs\graceful-fs.js:142:5)
        at OpenReq.done (D:\testyo\node_modules\grunt-contrib-imagemin\node_modules\gifsicle\node_modules\bin-wrapper\node_modules\download\node_modules\decompress\node_modules\rimraf\node_modules\graceful-fs\graceful-fs.js:64:22)
        at OpenReq.Req.done (D:\testyo\node_modules\grunt-contrib-imagemin\node_modules\jpegtran-bin\node_modules\bin-wrapper\node_modules\download\node_modules\decompress\node_modules\tar\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:142:5)
        at OpenReq.done (D:\testyo\node_modules\grunt-contrib-imagemin\node_modules\jpegtran-bin\node_modules\bin-wrapper\node_modules\download\node_modules\decompress\node_modules\tar\node_modules\fstream\node_modules\graceful-fs\graceful-fs.js:64:22) Use --force to continue.

    Aborted due to warnings.
```

The first one is easily fixed; any advice what causes the second problem?

**Comment by haydenbleasel** [comment]
1st problem was fixed in https://github.com/yeoman/generator-webapp/pull/192 (NPM dist hasn't been updated lately).

2nd problem is clearly a Compass error, similar to http://stackoverflow.com/questions/19498621/bower-components-folder-is-missing-from-yeoman-generated-web-site.

Try checking your Compass version with `compass version` or re-installing Compass with `gem install compass`.
