### ISSUE TITLE
grunt serve not working

### ISSUE THREAD

**Issue by gerbil** [yeoman/generator-webapp_DEPRECATED#319]
Running "concurrent:server" (concurrent) task
    <code>Warning:
C:\Users\jurijkob\Downloads\Iphone\angular-test\node_modules\grunt-contrib-compass\node_modules\tmp\lib\tmp.js:261
throw err;
^
TypeError: Cannot read property 'stdout' of undefined
at compile (C:\Users\jurijkob\Downloads\Iphone\angular-test\node_modules\grunt-contrib-compass\tasks\compass.js:37:10)
at C:\Users\jurijkob\Downloads\Iphone\angular-test\node_modules\grunt-contrib-compass\tasks\compass.js:68:7
at C:\Users\jurijkob\Downloads\Iphone\angular-test\node_modules\grunt-contrib-compass\tasks\lib\compass.js:121:11
at _fileCreated (C:\Users\jurijkob\Downloads\Iphone\angular-test\node_modules\grunt-contrib-compass\node_modules\tmp\lib\tmp.js:172:7)
at OpenReq.Req.done (C:\Users\jurijkob\Downloads\Iphone\angular-test\node_modules\karma\node_modules\graceful-fs\graceful-fs.js:143:5)
at OpenReq.done (C:\Users\jurijkob\Downloads\Iphone\angular-test\node_modules\karma\node_modules\graceful-fs\graceful-fs.js:63:22)
at OpenReq.Req.done (C:\Users\jurijkob\Downloads\Iphone\angular-test\node_modules\grunt-google-cdn\node_modules\bower\node_modules\graceful-fs\graceful-fs.js:143:5)
at OpenReq.done (C:\Users\jurijkob\Downloads\Iphone\angular-test\node_modules\grunt-google-cdn\node_modules\bower\node_modules\graceful-fs\graceful-fs.js:63:22)
at OpenReq.Req.done (C:\Users\jurijkob\Downloads\Iphone\angular-test\node_modules\grunt-google-cdn\node_modules\google-cdn\node_modules\bower\node_modul
es\graceful-fs\graceful-fs.js:143:5)
at OpenReq.done (C:\Users\jurijkob\Downloads\Iphone\angular-test\node_modules\grunt-google-cdn\node_modules\google-cdn\node_modules\bower\node_modules\graceful-fs\graceful-fs.js:63:22) 
Use --force to continue.
Aborted due to warnings.</code>

**Comment by addyosmani** [comment]
Could you share what options you selected when you ran into this issue? Also please confirm if you were definitely using `generator-webapp` as it seems you're doing some Angular testing.

**Comment by eddiemonge** [comment]
@gerbil still there?

**Comment by eddiemonge** [comment]
Closing due to inactivity. Will re-open if necessary
