### ISSUE TITLE
Yo WebApp Crashes

### ISSUE THREAD

**Issue by jtryan** [yeoman/generator-webapp_DEPRECATED#325]
Error:

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Appgenerator.EventEmitter.emit (events.js:74:15)
    at done (/Users/john/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/base.js:318:16)
    at /Users/john/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:232:13
    at /Users/john/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:113:21
    at /Users/john/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:24:16
    at /Users/john/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:229:17
    at /Users/john/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:516:34
    at Appgenerator.<anonymous> (/Users/john/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/actions/install.js:43:7)
    at ChildProcess.EventEmitter.emit (events.js:117:20)

**Comment by addyosmani** [comment]
What OS are you on and what version of yo are you using?

**Comment by jtryan** [comment]
OS x 10.9.2
yo version: 1.1.2

I just installed the git repo version and it runs, but threw a few errors on some optional dependencies.
pngquant-bin@0.1.7

There were others, but I went back and ran nom install -g to bring them in locally. That is the only one left.

**Comment by jtryan** [comment]
Additionally on the git version I was installing all 3 options.
On the npm repo version I only tried to install bootstrap.

**Comment by eddiemonge** [comment]
What options did you select? Did you change anything before you ran grunt serve?

**Comment by eddiemonge** [comment]
Closing due to inactivity. Will re-open if needed.
