### ISSUE TITLE
looks like maybe some 404s? not sure?

### ISSUE THREAD

**Issue by sygint** [yeoman/generator-webapp_DEPRECATED#336]
natas@Satan-Ubuntu13:~/Projects/demo-webapp$ yo webapp
...

> pngquant-bin@0.1.7 postinstall /home/natas/Projects/demo-webapp/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/pngquant-bin
> node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../lang/deepClone'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/natas/Projects/demo-webapp/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/mout/object/merge.js:2:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm WARN optional dep failed, continuing pngquant-bin@0.1.7

> optipng-bin@0.3.3 postinstall /home/natas/Projects/demo-webapp/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/optipng-bin
> node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module '../lang/deepClone'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/natas/Projects/demo-webapp/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/mout/object/merge.js:2:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm WARN optional dep failed, continuing optipng-bin@0.3.3

> gifsicle@0.1.5 postinstall /home/natas/Projects/demo-webapp/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/gifsicle
> node index.js

**Comment by sindresorhus** [comment]
Looks like you're having an issue installing grunt-contrib-imagemin. Open an issue there.

**Comment by kevva** [comment]
https://github.com/gruntjs/grunt-contrib-imagemin/issues/183

**Comment by sygint** [comment]
this issue was fixed with:
$ rm -rf ~/.npm
$ npm cache clear

thanks

**Comment by monarksingh** [comment]
Facing the same issue, tried what gnarmedia suggested, didn't worked for me.
