### ISSUE TITLE
"yo webapp" getting stuck at "grunt-contrib-connect@0.7.1"

### ISSUE THREAD

**Issue by monarksingh** [yeoman/generator-webapp_DEPRECATED#339]
First thing, I am not sure due to which component this issue is occuring.

Running Windows 8.1 64bits, Node v0.10.22, NPM v1.3.14.

ran "yo webapp" and it got stuck at below point, any hints guys. I tried cleaning npm cache and re-installing (Node, Generator), but nothing worked

> node install.js

Download already available at C:\Users\MONARK~1\AppData\Local\Temp\phantomjs\pha
ntomjs-1.9.7-windows.zip
Extracting zip contents
Copying extracted folder C:\Users\MONARK~1\AppData\Local\Temp\phantomjs\phantomj
s-1.9.7-windows.zip-extract-1397302037560\phantomjs-1.9.7-windows -> F:\Work\Per
sonnalProject\GVK_4\node_modules\grunt-mocha\node_modules\grunt-lib-phantomjs\no
de_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at F:\Work\PersonnalProject\GVK_4\node_modules\
grunt-mocha\node_modules\grunt-lib-phantomjs\node_modules\phantomjs\lib\phantom\
phantomjs.exe
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/fstream
npm http 304 https://registry.npmjs.org/block-stream
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/punycode
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/graceful-fs
npm http 304 https://registry.npmjs.org/graceful-fs

> pngquant-bin@0.1.7 postinstall F:\Work\PersonnalProject\GVK_4\node_modules\gru
> nt-contrib-imagemin\node_modules\image-min\node_modules\pngquant-bin
> node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'mout/string/endsWith'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (F:\Work\PersonnalProject\GVK_4\node_modules\grunt-con
trib-imagemin\node_modules\image-min\node_modules\map-key\index.js:4:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm WARN optional dep failed, continuing pngquant-bin@0.1.7
npm http GET https://registry.npmjs.org/punycode
npm http GET https://registry.npmjs.org/hoek
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp

> jpegtran-bin@0.2.6 postinstall F:\Work\PersonnalProject\GVK_4\node_modules\gru
> nt-contrib-imagemin\node_modules\image-min\node_modules\jpegtran-bin
> node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'mout/string/endsWith'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (F:\Work\PersonnalProject\GVK_4\node_modules\grunt-con
trib-imagemin\node_modules\image-min\node_modules\map-key\index.js:4:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm http GET https://registry.npmjs.org/stream-counter
npm http GET https://registry.npmjs.org/readable-stream
npm http 304 https://registry.npmjs.org/punycode

> optipng-bin@0.3.3 postinstall F:\Work\PersonnalProject\GVK_4\node_modules\grun
> t-contrib-imagemin\node_modules\image-min\node_modules\optipng-bin
> node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'mout/string/endsWith'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (F:\Work\PersonnalProject\GVK_4\node_modules\grunt-con
trib-imagemin\node_modules\image-min\node_modules\map-key\index.js:4:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm http 304 https://registry.npmjs.org/stream-counter
npm http 304 https://registry.npmjs.org/boom
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/cryptiles
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/readable-stream
npm WARN optional dep failed, continuing jpegtran-bin@0.2.6
npm http GET https://registry.npmjs.org/isarray/0.0.1
npm http GET https://registry.npmjs.org/string_decoder
npm http GET https://registry.npmjs.org/core-util-is
npm http GET https://registry.npmjs.org/inherits
npm WARN optional dep failed, continuing optipng-bin@0.3.3

> gifsicle@0.1.5 postinstall F:\Work\PersonnalProject\GVK_4\node_modules\grunt-c
> ontrib-imagemin\node_modules\image-min\node_modules\gifsicle
> node index.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'mout/string/endsWith'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (F:\Work\PersonnalProject\GVK_4\node_modules\grunt-con
trib-imagemin\node_modules\image-min\node_modules\map-key\index.js:4:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm WARN optional dep failed, continuing gifsicle@0.1.5
npm http 304 https://registry.npmjs.org/string_decoder
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/core-util-is
npm http 304 https://registry.npmjs.org/isarray/0.0.1
grunt-contrib-copy@0.5.0 node_modules\grunt-contrib-copy

grunt-rev@0.1.0 node_modules\grunt-rev

grunt-contrib-concat@0.3.0 node_modules\grunt-contrib-concat

grunt-usemin@2.1.1 node_modules\grunt-usemin
├── debug@0.7.4
└── lodash@1.0.1

grunt-contrib-clean@0.5.0 node_modules\grunt-contrib-clean
└── rimraf@2.2.6

time-grunt@0.3.1 node_modules\time-grunt
├── date-time@0.1.1
├── pretty-ms@0.1.0
├── hooker@0.2.3
├── text-table@0.2.0
└── chalk@0.4.0 (has-color@0.1.6, ansi-styles@1.0.0, strip-ansi@0.1.1)

grunt-newer@0.7.0 node_modules\grunt-newer
├── async@0.2.10
└── rimraf@2.2.6

jshint-stylish@0.1.5 node_modules\jshint-stylish
├── text-table@0.2.0
└── chalk@0.4.0 (ansi-styles@1.0.0, strip-ansi@0.1.1, has-color@0.1.6)

grunt-contrib-htmlmin@0.2.0 node_modules\grunt-contrib-htmlmin
├── html-minifier@0.5.6
├── each-async@0.1.2
├── pretty-bytes@0.1.0
└── chalk@0.4.0 (ansi-styles@1.0.0, has-color@0.1.6, strip-ansi@0.1.1)

grunt-concurrent@0.5.0 node_modules\grunt-concurrent
├── pad-stdio@0.1.1 (lpad@0.2.1)
└── async@0.2.10

grunt-contrib-cssmin@0.9.0 node_modules\grunt-contrib-cssmin
├── clean-css@2.1.8 (commander@2.1.0)
├── chalk@0.4.0 (has-color@0.1.6, ansi-styles@1.0.0, strip-ansi@0.1.1)
└── maxmin@0.1.0 (pretty-bytes@0.1.0, gzip-size@0.1.1)

grunt-contrib-jshint@0.9.2 node_modules\grunt-contrib-jshint
├── hooker@0.2.3
└── jshint@2.4.4 (console-browserify@0.1.6, underscore@1.4.4, exit@0.1.2, cli@0.
4.5, minimatch@0.2.14, shelljs@0.1.4, htmlparser2@3.3.0)

grunt-modernizr@0.5.2 node_modules\grunt-modernizr
├── colors@0.6.2
├── promised-io@0.3.4
├── uglify-js@1.3.3
└── request@2.27.0 (json-stringify-safe@5.0.0, aws-sign@0.3.0, forever-agent@0.5
.2, qs@0.6.6, tunnel-agent@0.3.0, oauth-sign@0.3.0, cookie-jar@0.3.0, mime@1.2.1
1, node-uuid@1.4.1, form-data@0.1.2, http-signature@0.10.0, hawk@1.0.0)

grunt-contrib-watch@0.6.1 node_modules\grunt-contrib-watch
├── async@0.2.10
├── lodash@2.4.1
├── tiny-lr-fork@0.0.5 (debug@0.7.4, faye-websocket@0.4.4, noptify@0.0.3, qs@0.5
.6)
└── gaze@0.5.1 (globule@0.1.0)

grunt-contrib-uglify@0.4.0 node_modules\grunt-contrib-uglify
├── chalk@0.4.0 (has-color@0.1.6, strip-ansi@0.1.1, ansi-styles@1.0.0)
├── uglify-js@2.4.13 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7,
source-map@0.1.33)
└── maxmin@0.1.0 (pretty-bytes@0.1.0, gzip-size@0.1.1)

grunt-autoprefixer@0.7.2 node_modules\grunt-autoprefixer
├── diff@1.0.8
├── chalk@0.4.0 (strip-ansi@0.1.1, ansi-styles@1.0.0, has-color@0.1.6)
└── autoprefixer@1.1.20140410 (fs-extra@0.8.1, postcss@0.3.4)

grunt-svgmin@0.4.0 node_modules\grunt-svgmin
├── each-async@0.1.2
├── pretty-bytes@0.1.0
├── chalk@0.4.0 (has-color@0.1.6, ansi-styles@1.0.0, strip-ansi@0.1.1)
└── svgo@0.4.4 (colors@0.6.2, whet.extend@0.9.9, coa@0.4.0, sax@0.6.0, js-yaml@2
.1.3)

grunt-mocha@0.4.10 node_modules\grunt-mocha
├── lodash@2.3.0
├── mocha@1.14.0 (debug@0.8.0, diff@1.0.7, growl@1.7.0, commander@2.0.0, mkdirp@
0.3.5, jade@0.26.3, glob@3.2.3)
└── grunt-lib-phantomjs@0.4.0 (semver@1.0.14, eventemitter2@0.4.13, temporary@0.
0.8, phantomjs@1.9.7-3)

grunt@0.4.4 node_modules\grunt
├── dateformat@1.0.2-1.2.3
├── which@1.0.5
├── eventemitter2@0.4.13
├── getobject@0.1.0
├── rimraf@2.2.6
├── colors@0.6.2
├── grunt-legacy-util@0.1.2
├── async@0.1.22
├── hooker@0.2.3
├── exit@0.1.2
├── nopt@1.0.10 (abbrev@1.0.4)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.15)
└── findup-sync@0.1.3 (glob@3.2.9, lodash@2.4.1)

load-grunt-tasks@0.4.0 node_modules\load-grunt-tasks
├── multimatch@0.1.0 (minimatch@0.2.14, lodash@2.4.1)
└── findup-sync@0.1.3 (glob@3.2.9, lodash@2.4.1)

grunt-bower-install@1.4.0 node_modules\grunt-bower-install
├── wiredep@1.4.3 (chalk@0.1.1, through2@0.4.1, glob@3.2.9, lodash@1.3.1)
└── bower-config@0.5.0 (osenv@0.0.3, graceful-fs@2.0.3, optimist@0.6.1, mout@0.6
.0)

grunt-contrib-imagemin@0.6.1 node_modules\grunt-contrib-imagemin
├── pretty-bytes@0.1.0
├── mkdirp@0.3.5
├── async@0.2.10
├── chalk@0.4.0 (strip-ansi@0.1.1, ansi-styles@1.0.0, has-color@0.1.6)
└── image-min@0.2.3 (map-key@0.1.1, filesize@2.0.3, win-spawn@2.0.0, stream-comb
iner@0.0.4, multipipe@0.0.2, concat-stream@1.4.4, through2@0.4.1, mout@0.9.1)

grunt-contrib-connect@0.7.1 node_modules\grunt-contrib-connect
├── connect-livereload@0.3.2
├── open@0.0.4
├── async@0.2.10
├── portscanner@0.2.2 (async@0.1.15)
└── connect@2.13.1 (uid2@0.0.3, methods@0.1.0, debug@0.8.0, cookie-signature@1.0
.1, fresh@0.2.0, pause@0.0.1, qs@0.6.6, bytes@0.2.1, raw-body@1.1.3, batch@0.5.0
, buffer-crc32@0.2.1, cookie@0.1.0, compressible@1.0.0, negotiator@0.3.0, send@0
.1.4, multiparty@2.2.0)

**Comment by monarksingh** [comment]
Was able to resolve this. my "path" env var was messed up(specially where GIT was specified), due to which bower which is dependent on GIT, was not able to locate it, causing it to fail at downloading some dependency I guess.

Root Cause: During "yo install" Bower was not getting its hands on GIT.
Make sure : Run check whether bower is working correctly before running "yo webapp"(or any another generator)

This can be marked as closed
