### ISSUE TITLE
Error running the generator

### ISSUE THREAD

**Issue by rizkysyazuli** [yeoman/generator-webapp_DEPRECATED#370]
I got this when running `yo webapp`

```
/usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/util/engines.js:32
  source = _.template(source)(data);
             ^
TypeError: Object function lodash(value) {
      // don't wrap if already wrapped, even if wrapped by a different `lodash` constructor
      return (value && typeof value == 'object' && !isArray(value) && hasOwnProperty.call(value, '__wrapped__'))
       ? value
       : new lodashWrapper(value);
    } has no method 'template'
    at Appgenerator.underscore [as _engine] (/usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/util/engines.js:32:14)
    at Appgenerator.engine (/usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/actions/actions.js:303:10)
    at Appgenerator.template (/usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/actions/actions.js:281:15)
    at Appgenerator.gruntfile (/usr/local/lib/node_modules/generator-webapp/app/index.js:92:8)
    at /usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/base.js:341:43
    at /usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
    at iterate (/usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:134:13)
    at /usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:145:25
    at /usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:229:17
```

**Comment by eddiemonge** [comment]
what version of the generator?

**Comment by rizkysyazuli** [comment]
0.4.9

**Comment by eddiemonge** [comment]
try running `npm install` again

**Comment by rizkysyazuli** [comment]
re-installing yeoman and the generator seems to fix the problem.

i should have think of that. many computer problems can be solved by re-installing the app or restarting my computer :smile:

**Comment by jcdalton2201** [comment]
it appears that there is a private version of lodash (emmetio/lodash) that if you have install atom and emmet then you might have this version of lodash cache if you run 
npm cache clean
this should fix the issue also.
