### ISSUE TITLE
Critical errors, 100% failure

### ISSUE THREAD

**Issue by ghost** [yeoman/generator-webapp_DEPRECATED#385]
Something is wrong with the webapp generator of late. When I go into a director and run `yo webapp`, I get errors:

```
> node index.js

\
module.js:340
    throw err;
          ^
Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/bob/mytest/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/map-key/index.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

And more errors..

```
/Users/bob/mytest/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/map-key/node_modules/lodash/dist/lodash.js:4321
    /**
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/bob/mytest/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/map-key/index.js:3:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

And then when trying to run `grunt serve`:

```
        Warning: Syntax error: File to import not found or unreadable: ../../bower_components/bootstrap-sass-official/vendor/assets/stylesheets/bootstrap.scss.
                  Load paths:
                    /Users/bob/mytest
                    /Users/bob/mytest/app/styles
                    /Users/bob/mytest/bower_components
            on line 4 of app/styles/main.scss
      Use --trace for backtrace. Use --force to continue.

        Aborted due to warnings.
```

**Comment by ghost** [comment]
Addendum: checked "Bootstrap" and "Sass" options, left Modernizr unchecked. Answered "no" to the libsass question.

**Comment by silvenon** [comment]
Which version? 0.4.9?

**Comment by ghost** [comment]
Yes, 0.4.9.

**Comment by eddiemonge** [comment]
Did you try running `npm install` again? Sometimes npm doesnt install everything correctly

**Comment by eddiemonge** [comment]
possible duplicate of #349

**Comment by ghost** [comment]
`npm install` does not help.

**Comment by silvenon** [comment]
The second issue is a duplicate of #388.
