### ISSUE TITLE
yo webapp is throwing errors

### ISSUE THREAD

**Issue by reesejohn69** [yeoman/generator-webapp_DEPRECATED#431]
Getting the following errors when I'm running `yo webapp` command.

``` Bash
john app-v3 (master) $ yo webapp

     _-----_
    |       |
    |--(o)--|   .--------------------------.
   `---------´  |    Welcome to Yeoman,    |
    ( _´U`_ )   |   ladies and gentlemen!  |
    /___A___\   '__________________________'
     |  ~  |
   __'.___.'__
 ´   `  |° ´ Y `

Out of the box I include HTML5 Boilerplate, jQuery, and a Gruntfile.js to build your app.
[?] What more would you like? Bootstrap
   create Gruntfile.js
   create package.json
   create .gitignore
   create .gitattributes
   create bower.json
   create .jshintrc
   create .editorconfig
   create app/favicon.ico
   create app/404.html
   create app/robots.txt
   create app/.htaccess
   create app/styles/main.css
   create app/index.html
   create app/scripts/main.js


I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


npm WARN package.json app-v3@0.0.0 No description
npm WARN package.json app-v3@0.0.0 No repository field.
npm WARN package.json app-v3@0.0.0 No README data
bower cached        git://github.com/twbs/bootstrap.git#3.0.3
bower validate      3.0.3 against git://github.com/twbs/bootstrap.git#~3.0.3
bower cached        git://github.com/jquery/jquery.git#1.11.1
bower validate      1.11.1 against git://github.com/jquery/jquery.git#~1.11.0
bower install       jquery#1.11.1
bower install       bootstrap#3.0.3
\
jquery#1.11.1 bower_components/jquery

bootstrap#3.0.3 bower_components/bootstrap
└── jquery#1.11.1
npm WARN deprecated object-keys@0.2.0: Please update to the latest object-keys

> phantomjs@1.9.7-15 install /Users/john/Sites/test/app-v3/node_modules/grunt-mocha/node_modules/grunt-lib-phantomjs/node_modules/phantomjs
> node install.js

Download already available at /var/folders/4n/t4jk8mts26bgwbv61084b2v80000gn/T/phantomjs/phantomjs-1.9.7-macosx.zip
Extracting zip contents
Copying extracted folder /var/folders/4n/t4jk8mts26bgwbv61084b2v80000gn/T/phantomjs/phantomjs-1.9.7-macosx.zip-extract-1408967154886/phantomjs-1.9.7-macosx -> /Users/john/Sites/test/app-v3/node_modules/grunt-mocha/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/john/Sites/test/app-v3/node_modules/grunt-mocha/node_modules/grunt-lib-phantomjs/node_modules/phantomjs/lib/phantom/bin/phantomjs

> optipng-bin@0.3.2 postinstall /Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/optipng-stream-bin/node_modules/optipng-bin
> node index.js

/
> pngquant-bin@0.1.7 postinstall /Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/pngquant-bin
> node index.js


> gifsicle@0.1.7 postinstall /Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/gifsicle
> node index.js


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Invalid URI ""
    at Request.init (/Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/request/index.js:203:24)
    at new Request (/Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/request/index.js:124:8)
    at Function.request [as get] (/Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/node_modules/request/index.js:1255:11)
    at module.exports (/Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/download/download.js:26:23)
    at /Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/gifsicle/node_modules/bin-wrapper/index.js:100:20
    at /Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/gifsicle/node_modules/bin-wrapper/index.js:140:24
    at ChildProcess.<anonymous> (/Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/gifsicle/node_modules/bin-wrapper/node_modules/bin-check/index.js:39:24)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
npm WARN optional dep failed, continuing gifsicle@0.1.7

> jpegtran-bin@0.2.8 postinstall /Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/jpegtran-bin
> node index.js


events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Invalid URI ""
    at Request.init (/Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/request/index.js:203:24)
    at new Request (/Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/request/index.js:124:8)
    at Function.request [as get] (/Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/node_modules/request/index.js:1255:11)
    at module.exports (/Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/download/download.js:26:23)
    at /Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/jpegtran-bin/node_modules/bin-wrapper/index.js:100:20
    at /Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/jpegtran-bin/node_modules/bin-wrapper/index.js:140:24
    at ChildProcess.<anonymous> (/Users/john/Sites/test/app-v3/node_modules/grunt-contrib-imagemin/node_modules/image-min/node_modules/jpegtran-bin/node_modules/bin-wrapper/node_modules/bin-check/index.js:39:24)
    at ChildProcess.emit (events.js:98:17)
    at Process.ChildProcess._handle.onexit (child_process.js:810:12)
npm WARN optional dep failed, continuing jpegtran-bin@0.2.8
npm ERR! peerinvalid The package grunt does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-contrib-copy@0.5.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-concat@0.3.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-uglify@0.4.1 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-jshint@0.9.2 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-cssmin@0.9.0 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-contrib-connect@0.7.1 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-clean@0.5.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-htmlmin@0.2.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-bower-install@1.4.1 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-imagemin@0.6.1 wants grunt@^0.4.0
npm ERR! peerinvalid Peer grunt-contrib-watch@0.6.1 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-autoprefixer@0.7.6 wants grunt@~0.4.2
npm ERR! peerinvalid Peer grunt-usemin@2.1.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-mocha@0.4.11 wants grunt@~0.4
npm ERR! peerinvalid Peer grunt-newer@0.7.0 wants grunt@~0.4.1
npm ERR! peerinvalid Peer grunt-svgmin@0.4.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-concurrent@0.5.0 wants grunt@~0.4.0

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/john/Sites/test/app-v3
npm ERR! node -v v0.10.31
npm ERR! npm -v 2.0.0-beta.0
npm ERR! code EPEERINVALID
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/john/Sites/test/app-v3/npm-debug.log
npm ERR! not ok code 0

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Appgenerator.emit (events.js:74:15)
    at done (/usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/base.js:318:16)
    at /usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:232:13
    at /usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:113:21
    at /usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:24:16
    at /usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:229:17
    at /usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/node_modules/async/lib/async.js:516:34
    at Appgenerator.<anonymous> (/usr/local/lib/node_modules/generator-webapp/node_modules/yeoman-generator/lib/actions/install.js:43:7)
    at ChildProcess.emit (events.js:117:20)
john app-v3 (master) $
```

**bower.json**

``` JS
{
  "name": "app-v3",
  "private": true,
  "dependencies": {
    "bootstrap": "~3.0.3",
    "jquery": "~1.11.0"
  },
  "devDependencies": {}
}
```

**package.json**

``` JS
{
  "name": "app-v3",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {
    "grunt": "~0.4.1",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-contrib-jshint": "~0.9.2",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-connect": "~0.7.1",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-htmlmin": "~0.2.0",
    "grunt-bower-install": "~1.4.0",
    "grunt-contrib-imagemin": "~0.6.0",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-rev": "~0.1.0",
    "grunt-autoprefixer": "~0.7.2",
    "grunt-usemin": "~2.1.0",
    "grunt-mocha": "~0.4.10",
    "grunt-newer": "~0.7.0",
    "grunt-svgmin": "~0.4.0",
    "grunt-concurrent": "~0.5.0",
    "load-grunt-tasks": "~0.4.0",
    "time-grunt": "~0.3.1",
    "jshint-stylish": "~0.1.5"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}
```

**Additional Information:**
- node@v0.10.3
- npm@2.0.0-beta.0
- yo@1.2.1
- bower@1.3.9
- generator-webapp@0.4.9
- grunt-cli@0.1.13
- grunt@v0.4.5

**Comment by silvenon** [comment]
You have beta version of npm, which is no good. Run:

``` sh
$ npm cache clean
$ npm update -g npm
```

which should roll back to the stable version and try again.

**Comment by reesejohn69** [comment]
Thanks a lot. It solved the issue.

`npm` came with `node`, which I installed using Homebrew.

**Comment by silvenon** [comment]
Great! Yeah, I don't know why they're using beta in their recipe.
