### ISSUE TITLE
grunt serve fails

### ISSUE THREAD

**Issue by Johnz86** [yeoman/generator-webapp_DEPRECATED#454]
Whenever I run the `grunt serve` command I get this warning:

``` bash
Running "serve" task

Running "clean:server" (clean) task
>> 1 path cleaned.

Running "wiredep:app" (wiredep) task

Running "wiredep:sass" (wiredep) task

Running "concurrent:server" (concurrent) task

Running "copy:styles" (copy) task


Done, without errors.
    Warning: DEPRECATION WARNING: Passing --sourcemap without a value is deprecated.
    Sourcemaps are now generated by default, so this flag has no effect.
    NoMethodError: undefined method `zero?' for nil:NilClass
      Use --trace for backtrace. Use --force to continue.

    Aborted due to warnings.
```

If I run the command with `grunt  serve --force`
The warning is not present, the task is running, but grunt server is not running.
When I execute `yo webapp --version` i will get: `1.2.1`.
 I m running on Windows 8 os with node --version:`v0.10.31`

If i try to run my older projects which used webapp generator and have older version Gruntfile.js and run `grunt serve` everything seems to be fine. There are no warnings and grunt server starts.

**Comment by Johnz86** [comment]
If I start new project with `yo webapp` command and do not include the sass option, and then execute `grunt serve` everything seems to be fine. 
My last working Gruntfile.js that worked with sass option was 
`Generated on 2014-05-30 using generator-webapp 0.4.9`
The Gruntfile.js that is not working for me:
`// Generated on 2014-09-23 using
// generator-webapp 0.5.0`

**Comment by silvenon** [comment]
Duplicate of #444, see https://github.com/yeoman/generator-webapp/issues/444#issuecomment-55191258. This is fixed in 8e72360456acbf5e3720b991b9c82b5c7c9be877, it's not yet released.

**Comment by Johnz86** [comment]
My problem is probably not a duplicate of #444.
In version 0.5.0 I have this in my Gruntfile:

```
sass: {
      options: {
        sourcemap: true,
        loadPath: 'bower_components'
      },
```

I removed `sourcemap: true,` from my Grunt file, as the #444 suggest for workaround, I still have an issue:

```
sass: {
      options: {
        loadPath: 'bower_components'
      },
```

The result after `grunt serve` is:

```
Done, without errors.
    Warning: NoMethodError: undefined method `zero?' for nil:NilClass
      Use --trace for backtrace. Use --force to continue.

    Aborted due to warnings.
```

The grunt server will still not run.

**Comment by silvenon** [comment]
What version of grunt-contrib-sass are you using?

**Comment by Johnz86** [comment]
Here is my package.json in project that can not run `grunt serve` successfully.

```
{
  "name": "yo-webapp-test",
  "devDependencies": {
    "apache-server-configs": "^2.7.1",
    "grunt": "^0.4.5",
    "grunt-contrib-copy": "^0.5.0",
    "grunt-contrib-concat": "^0.5.0",
    "grunt-contrib-uglify": "^0.5.1",
    "grunt-contrib-sass": "^0.7.3",
    "grunt-contrib-jshint": "^0.10.0",
    "grunt-contrib-cssmin": "^0.10.0",
    "grunt-contrib-connect": "^0.8.0",
    "grunt-contrib-clean": "^0.6.0",
    "grunt-contrib-htmlmin": "^0.3.0",
    "grunt-wiredep": "^1.7.0",
    "grunt-contrib-imagemin": "^0.8.0",
    "grunt-contrib-watch": "^0.6.1",
    "grunt-rev": "^0.1.0",
    "grunt-autoprefixer": "^1.0.0",
    "grunt-usemin": "^2.3.0",
    "grunt-mocha": "^0.4.10",
    "grunt-newer": "^0.7.0",
    "grunt-svgmin": "^0.4.0",
    "grunt-concurrent": "^0.5.0",
    "load-grunt-tasks": "^0.4.0",
    "time-grunt": "^0.4.0",
    "jshint-stylish": "^0.4.0"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}
```

My last working configuration has this package.json file:

```
{
  "name": "pagetest-speed",
  "version": "0.0.0",
  "dependencies": {},
  "devDependencies": {
    "grunt": "~0.4.1",
    "grunt-contrib-copy": "~0.5.0",
    "grunt-contrib-concat": "~0.3.0",
    "grunt-contrib-uglify": "~0.4.0",
    "grunt-sass": "~0.11.0",
    "grunt-contrib-jshint": "~0.9.2",
    "grunt-contrib-cssmin": "~0.9.0",
    "grunt-contrib-connect": "~0.7.1",
    "grunt-contrib-clean": "~0.5.0",
    "grunt-contrib-htmlmin": "~0.2.0",
    "grunt-bower-install": "~1.4.0",
    "grunt-contrib-imagemin": "~0.6.0",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-rev": "~0.1.0",
    "grunt-autoprefixer": "~0.7.2",
    "grunt-usemin": "~2.1.0",
    "grunt-mocha": "~0.4.10",
    "grunt-newer": "~0.7.0",
    "grunt-svgmin": "~0.4.0",
    "grunt-concurrent": "~0.5.0",
    "load-grunt-tasks": "~0.4.0",
    "time-grunt": "~0.3.1",
    "jshint-stylish": "~0.1.5"
  },
  "engines": {
    "node": ">=0.10.0"
  }
}
```

**Comment by Johnz86** [comment]
I tried to update to newer version of sass. I went from 3.4.0 > 3.4.5. Then I got more human readable message.

```
Done, without errors.
    Warning: NoMethodError: undefined method `ArgumentError' for Sass::Util:Module
      Use --trace for backtrace. Use --force to continue.

    Aborted due to warnings.
```

**Comment by Johnz86** [comment]
I discovered source of the problem. Fault is again path names resolution in windows. I added a trace option into grunt:server task and i got:

```
D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.5/lib/sass/util.rb:702:in `rescue in relative_path_from': undefined method `ArgumentError' for Sass::Util:Module (NoMethodError
        from D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.5/lib/sass/util.rb:695:in `relative_path_from'
        from D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.5/lib/sass/importers/filesystem.rb:76:in `public_url'
        from D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.5/lib/sass/engine.rb:359:in `block in _render_with_sourcemap'
        from D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.5/lib/sass/util.rb:482:in `silence_warnings'
        from D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.5/lib/sass/engine.rb:357:in `_render_with_sourcemap'
        from D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.5/lib/sass/engine.rb:285:in `render_with_sourcemap'
        from D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.5/lib/sass/exec/sass_scss.rb:396:in `run'
        from D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.5/lib/sass/exec/sass_scss.rb:62:in `process_result'
        from D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.5/lib/sass/exec/base.rb:52:in `parse'
        from D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.5/lib/sass/exec/base.rb:19:in `parse!'
        from D:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/sass-3.4.5/bin/sass:13:in `<top (required)>'
        from D:/Ruby200-x64/bin/sass:23:in `load'
        from D:/Ruby200-x64/bin/sass:23:in `<main>'
Warning: Exited with error code 1 Use --force to continue.
```

Which got me inside the documentation of Sass Util. 
- (Pathname?) relative_path_from(path, from) 

This is like Pathname#relative_path_from except it accepts both strings and pathnames, it handles Windows path separators correctly, and it throws an error rather than crashing if the paths use different encodings (https://github.com/ruby/ruby/pull/713).

My project is placed on this path:
`D:\Tvorba\Sprostredkovaná práca\yo-webapp-test`
Which contains my native language characters.

After I placed the project on path, that contained only characters from english alphabet all went correctly and `grunt serve` worked.
Previous version of webapp generator did rely on "grunt-sass": "~0.11.0", which did not suffer this path name resolution problem. 

I will report this problem to grunt-contrib-sass.

**Comment by eddiemonge** [comment]
Ok thanks.
