### ISSUE TITLE
yo webapp run error

### ISSUE THREAD

**Issue by tristanisfeld** [yeoman/generator-webapp_DEPRECATED#549]
iojs v: 2.2.1
npm v:2.11.1

error trying to run yo webapp.

$ yo webapp
module.js:334
    throw err;
          ^
Error: Cannot find module 'number-is-nan'
    at Function.Module._resolveFilename (module.js:332:15)
    at Function.Module._load (module.js:282:25)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Program Files\iojs\node_modules\generator-webapp\node_modules\yeoman-generator\node_modules\download\node_modules\decompress\node_
modules\decompress-tar\node_modules\strip-dirs\node_modules\is-integer\node_modules\is-finite\index.js:2:19)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)

**Comment by tristanisfeld** [comment]
After uninstalling iojs and installing nodejs 0.12.4, the issue is resolved. This is an iojs breaking change, affecting yeoman. So not sure if relevant here.
