### ISSUE TITLE
ENOENT ENOENT, utime '/home/pbx06/test2/bower_components/bootstrap/LICENSE

### ISSUE THREAD

**Issue by pabx06** [yeoman/generator-webapp_DEPRECATED#553]
```
I'm all done. Running bower install & npm install for you to install the required dependencies. If this fails, try running the command yourself.


   create     test/spec/test.js
   create     test/index.html
bower bootstrap#~3.2.0          cached git://github.com/twbs/bootstrap.git#3.2.0
bower bootstrap#~3.2.0        validate 3.2.0 against git://github.com/twbs/bootstrap.git#~3.2.0
bower bootstrap#~3.2.0          cached git://github.com/twbs/bootstrap.git#3.2.0
bower bootstrap#~3.2.0        validate 3.2.0 against git://github.com/twbs/bootstrap.git#~3.2.0
bower chai#*                    cached git://github.com/chaijs/chai.git#3.0.0
bower chai#*                  validate 3.0.0 against git://github.com/chaijs/chai.git#*
bower mocha#*                   cached git://github.com/mochajs/mocha.git#2.2.5
bower mocha#*                 validate 2.2.5 against git://github.com/mochajs/mocha.git#*
bower jquery#>= 1.9.0           cached git://github.com/jquery/jquery.git#2.1.4
bower jquery#>= 1.9.0         validate 2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.0
bower jquery#>= 1.9.0           cached git://github.com/jquery/jquery.git#2.1.4
bower jquery#>= 1.9.0         validate 2.1.4 against git://github.com/jquery/jquery.git#>= 1.9.0
bower chai#~3.0.0              install chai#3.0.0
bower mocha#~2.2.5             install mocha#2.2.5
bower bootstrap#~3.2.0         install bootstrap#3.2.0
bower jquery#>= 1.9.0          install jquery#2.1.4
bower bootstrap#~3.2.0         install bootstrap#3.2.0
bower jquery#>= 1.9.0          install jquery#2.1.4
bower                           ENOENT ENOENT, utime '/home/pbx06/test2/bower_components/bootstrap/LICENSE'

Stack trace:
/home/pbx06/node-v0.12.4-linux-x64/lib/node_modules/bower/node_modules/fstream/lib/writer.js:306:21
FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)

Console trace:
Error
    at StandardRenderer.error (/home/pbx06/node-v0.12.4-linux-x64/lib/node_modules/bower/lib/renderers/StandardRenderer.js:82:37)
    at Logger.<anonymous> (/home/pbx06/node-v0.12.4-linux-x64/lib/node_modules/bower/bin/bower:110:22)
    at Logger.emit (events.js:107:17)
    at Logger.emit (/home/pbx06/node-v0.12.4-linux-x64/lib/node_modules/bower/node_modules/bower-logger/lib/Logger.js:29:39)
    at /home/pbx06/node-v0.12.4-linux-x64/lib/node_modules/bower/lib/commands/index.js:45:20
    at _rejected (/home/pbx06/node-v0.12.4-linux-x64/lib/node_modules/bower/node_modules/q/q.js:844:24)
    at /home/pbx06/node-v0.12.4-linux-x64/lib/node_modules/bower/node_modules/q/q.js:870:30
    at Promise.when (/home/pbx06/node-v0.12.4-linux-x64/lib/node_modules/bower/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/home/pbx06/node-v0.12.4-linux-x64/lib/node_modules/bower/node_modules/q/q.js:788:41)
    at /home/pbx06/node-v0.12.4-linux-x64/lib/node_modules/bower/node_modules/q/q.js:604:44
System info:
Bower version: 1.4.1
Node version: 0.12.4
OS: Linux 3.14.38-gentoo x64

bootstrap#3.2.0 bower_components/bootstrap
└── jquery#2.1.4

```

**Comment by pabx06** [comment]
```
grunt
Running "newer:jshint" (newer) task

Running "newer:jshint:all" (newer) task

Running "jshint:all" (jshint) task

test/spec/test.js
  line 4  col 3  'describe' is not defined.
  line 5  col 5  'describe' is not defined.
  line 6  col 7  'it' is not defined.

✖ 3 problems

Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-06-14 15:18:18 UTC)
loading tasks     992ms  ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇ 89%
newer:jshint:all   22ms  ▇▇▇ 2%
jshint:all        101ms  ▇▇▇▇▇▇▇▇▇▇ 9%
Total 1.1s

```

**Comment by silvenon** [comment]
No idea how the first one happens.

About the second one, do you have a `.jshintrc` file? Does it have `"mocha": true`?

**Comment by silvenon** [comment]
In the future, please try to poke around an issue and provide a better title, instead of just pasting output.

**Comment by silvenon** [comment]
Closing due to inactivity. I'll reopen when we get more feedback.
